### ISSUE TITLE
Upgrade to PureScript 0.11?

### ISSUE THREAD

**Issue by FranklinChen** [justinwoo/purescript-etch-sketch#1]
I think supporting PureScript 0.11 requires upgrading from Pux 7 to 9.

**Comment by justinwoo** [comment]
Updated: https://github.com/justinwoo/purescript-etch-sketch/commit/ff6435a00c35091f33ae4d923e6d0af809013c4e

I guess the big changes have been the change to use Smolder to render stuff and some API changes.

**Comment by FranklinChen** [comment]
Yeah. Thanks!
